/**
 * Custom Cloudflare Worker entry point
 * Implements OpenNext custom worker pattern with Durable Objects
 * Reference: https://opennext.js.org/cloudflare/howtos/custom-worker
 */

// Import OpenNext generated worker
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Generated by OpenNext build
import { default as opennextHandler } from './.open-next/worker.js';

// Export custom Durable Object
export { CounterDO } from './durable-objects/CounterDO';

// Re-export OpenNext built-in Durable Objects
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Generated by OpenNext build
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';

// Export default handler (required by Cloudflare Workers)
export default {
  fetch: opennextHandler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
