name = "portfolio"
main = ".open-next/worker.js"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]

# Environment variables 
[vars]
GITHUB_USERNAME = "ionutcnu"

# Static assets
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "portfolio-counter"
database_id = "10a10508-24ee-4010-aa16-9598e5920506"

# Analytics Engine binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# KV Namespace for caching
[[kv_namespaces]]
binding = "KV"
id = "a4f458cca56447288d7902164fc1ee60"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = false
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
